name: currency_pickers
description: Currency picker for flutter forked from Figen Güngör <figengungor1@gmail.com> repository country_pickers
version: 1.1.1
homepage: https://github.com/JoshLorDeveloper/currency_pickers

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
